# Generated by Django 4.0 on 2021-12-15 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('equipment_id', models.AutoField(primary_key=True, serialize=False)),
                ('equipment', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
                ('incorporation_date', models.DateField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('maintenance_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(max_length=15)),
                ('maintenance_type', models.CharField(max_length=20)),
                ('performed_by', models.CharField(max_length=30)),
                ('observations', models.CharField(max_length=300)),
                ('equipment_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Equipment.equipment')),
            ],
        ),
    ]
