# Generated by Django 4.0 on 2021-12-16 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Equipment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintenance',
            old_name='equipment_id',
            new_name='eq_id',
        ),
    ]
