# Generated by Django 4.0 on 2021-12-16 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipment', '0002_rename_equipment_id_maintenance_eq_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='warranty_date',
            field=models.DateField(max_length=20, null=True),
        ),
    ]
