# Generated by Django 4.0 on 2021-12-21 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipment', '0003_equipment_warranty_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenance',
            name='eq_id',
        ),
        migrations.AddField(
            model_name='maintenance',
            name='equipmentid',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
